name: example
description: Flutter Infinite Listview Example
version: 1.1.0

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  infinite_listview:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
